# This is a sample docker-compose file, Please follow the naming convention for the service and container name, all node
# names must begin with "Node" followed by their sequence number. For a three node cluster your service/container names
# should be Node1, Node2 and Node3 as shown below(for service names they will be lowercase). You can add additional
# parameters and configurations as required by your implementation.


version: "3.7"
services:
   node1:
     container_name : Node1
     image: node1
     build: Node/.
     environment:
     - container_name=Node1

   node2:
     container_name : Node2
     image: node1
     build: Node/.
     environment:
     - container_name=Node2

   node3:
     container_name : Node3
     image: node1
     build: Node/.
     environment:
     - container_name=Node3

   node4:
     container_name : Node4
     image: node1
     build: Node/.
     environment:
     - container_name=Node4

   node5:
     container_name : Node5
     image: node1
     build: Node/.
     environment:
     - container_name=Node5

   #Do not change the part below
   controller:
       container_name: Controller
       build: Controller/.
       stdin_open: true









